/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package otopark;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author asus
 */
public class AnaEkran extends javax.swing.JFrame {

    /**
     * Creates new form AnaEkran
     */
    public AnaEkran() {
        initComponents();
        setResizable(false);
        try {
      jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otopark/icon_klasoru/luxury_car_icon_80x80.png")));
jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otopark/icon_klasoru/103857_glass_search_magnifying_find_icon.png")));
jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otopark/icon_klasoru/user_icon_80x80_darker_blue.png")));
jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otopark/icon_klasoru/payment_icon_80x80.png")));

    } catch (Exception e) {
        e.printStackTrace(); // eksik ikon varsa burada görürüz
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new otopark.RoundedPanel();
        jLabel15 = new javax.swing.JLabel();
        uye_kaydi = new javax.swing.JButton();
        otopark_Giris_islemi = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        arama_islemleri = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        fiyat_belirleme = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Otopark Otomasyon");

        roundedPanel1.setBackground(new java.awt.Color(38, 43, 43));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\icon klasörü\\user_icon_80x80_darker_blue.png")); // NOI18N

        uye_kaydi.setBackground(new java.awt.Color(102, 102, 102));
        uye_kaydi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        uye_kaydi.setForeground(new java.awt.Color(255, 255, 255));
        uye_kaydi.setText("Üye Kaydi");
        uye_kaydi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uye_kaydiActionPerformed(evt);
            }
        });

        otopark_Giris_islemi.setBackground(new java.awt.Color(102, 102, 102));
        otopark_Giris_islemi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        otopark_Giris_islemi.setForeground(new java.awt.Color(255, 255, 255));
        otopark_Giris_islemi.setText("Otopark Giriş İşlemleri");
        otopark_Giris_islemi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otopark_Giris_islemiActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\icon klasörü\\luxury_car_icon_80x80.png")); // NOI18N

        arama_islemleri.setBackground(new java.awt.Color(102, 102, 102));
        arama_islemleri.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        arama_islemleri.setForeground(new java.awt.Color(255, 255, 255));
        arama_islemleri.setText("Arama İşlemleri");
        arama_islemleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arama_islemleriActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\icon klasörü\\103857_glass_search_magnifying_find_icon.png")); // NOI18N

        fiyat_belirleme.setBackground(new java.awt.Color(102, 102, 102));
        fiyat_belirleme.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fiyat_belirleme.setForeground(new java.awt.Color(255, 255, 255));
        fiyat_belirleme.setText("Fiyat Belirleme");
        fiyat_belirleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiyat_belirlemeActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\icon klasörü\\payment_icon_80x80.png")); // NOI18N

        label1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("OTOPARK İŞLEMLERİ");

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8))))
                            .addComponent(jLabel15)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fiyat_belirleme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(otopark_Giris_islemi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(uye_kaydi, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(arama_islemleri, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(otopark_Giris_islemi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(uye_kaydi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(27, 27, 27))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(arama_islemleri, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fiyat_belirleme, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void otopark_Giris_islemiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otopark_Giris_islemiActionPerformed
        //yeni pencereyi aç ve mevcut pencereyi kapat
                dispose();
                new Otopark_Girs().setVisible(true);
    }//GEN-LAST:event_otopark_Giris_islemiActionPerformed

    private void uye_kaydiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uye_kaydiActionPerformed
//yeni pencereyi aç ve mevcut pencereyi kapat
                JFrame anaEkran= new Uye_giris();
                anaEkran.setVisible(true);
                          //mevcut pencereyi kapat
                           JFrame frame =(JFrame)SwingUtilities.getWindowAncestor(this);
                          frame.dispose();
    }//GEN-LAST:event_uye_kaydiActionPerformed

    private void arama_islemleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arama_islemleriActionPerformed
        Arama_islemi aramaEkrani = new Arama_islemi();
    aramaEkrani.setVisible(true);

    // Mevcut pencereyi kapat:
    this.dispose(); // "this" AnaEkran'ı ifade eder
    }//GEN-LAST:event_arama_islemleriActionPerformed

    private void fiyat_belirlemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiyat_belirlemeActionPerformed
        JFrame anaEkran=new ucretler();
        anaEkran.setVisible(true);
        JFrame frame =(JFrame)SwingUtilities.getWindowAncestor(this);
        frame.dispose();
    }//GEN-LAST:event_fiyat_belirlemeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arama_islemleri;
    private javax.swing.JButton fiyat_belirleme;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private java.awt.Label label1;
    private javax.swing.JButton otopark_Giris_islemi;
    private otopark.RoundedPanel roundedPanel1;
    private javax.swing.JButton uye_kaydi;
    // End of variables declaration//GEN-END:variables
}
