/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package otopark;

import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class Arama_islemi extends javax.swing.JFrame {

    /**
     * Creates new form Arama_islemi
     */
    public Arama_islemi() {
        initComponents();
        try {
        URL geriIconURL = getClass().getResource("/otopark/icon_klasoru/6820523_back_interface_ui_ux_icon.png");
        if (geriIconURL != null) {
            geri.setIcon(new javax.swing.ImageIcon(geriIconURL));
        } else {
            System.out.println("Geri buton ikonu bulunamadı!");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new otopark.RoundedPanel();
        roundedPanel2 = new otopark.RoundedPanel();
        seccim_buttonu = new javax.swing.JComboBox<>();
        arama_yap_texfald = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        geri = new javax.swing.JButton();
        uye_sil = new javax.swing.JButton();
        aramaYap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        roundedPanel1.setBackground(new java.awt.Color(35, 35, 39));

        roundedPanel2.setBackground(new java.awt.Color(24, 24, 27));

        seccim_buttonu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        seccim_buttonu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Üye No", "Üye Adı", "Üye plaka", "" }));
        seccim_buttonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seccim_buttonuActionPerformed(evt);
            }
        });

        arama_yap_texfald.setBackground(new java.awt.Color(24, 24, 27));
        arama_yap_texfald.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        arama_yap_texfald.setForeground(new java.awt.Color(255, 255, 255));
        arama_yap_texfald.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seccim_buttonu, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(arama_yap_texfald, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(seccim_buttonu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arama_yap_texfald, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(228, 228, 231));
        jLabel1.setText("ÜYE ARAMA");

        geri.setBackground(new java.awt.Color(35, 35, 39));
        geri.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        geri.setBorder(null);
        geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriActionPerformed(evt);
            }
        });

        uye_sil.setBackground(new java.awt.Color(102, 102, 102));
        uye_sil.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        uye_sil.setForeground(new java.awt.Color(255, 255, 255));
        uye_sil.setText("Üye Sil");
        uye_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uye_silActionPerformed(evt);
            }
        });

        aramaYap.setBackground(new java.awt.Color(102, 102, 102));
        aramaYap.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        aramaYap.setForeground(new java.awt.Color(255, 255, 255));
        aramaYap.setText("Arama Yap");
        aramaYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aramaYapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(geri, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aramaYap, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(uye_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aramaYap, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(uye_sil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(geri, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void seccim_buttonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seccim_buttonuActionPerformed
        
    }//GEN-LAST:event_seccim_buttonuActionPerformed

    private void aramaYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aramaYapActionPerformed
      
    String secim = seccim_buttonu.getSelectedItem().toString();
String aranacak = arama_yap_texfald.getText();
String kolon = "";

if (secim.equals("Üye No")) {
    kolon = "uye_bilgisi.uye_no";
} else if (secim.equals("Üye Adı")) {
    kolon = "uye_bilgisi.ad";
} else if (secim.equals("Üye plaka")) {
    kolon = "arac_bilgi.plaka"; // burası önemli!
}

try {
   Connection con = DBConnection.getConnection();

    String sql = "SELECT * FROM uye_bilgisi " +
                 "INNER JOIN arac_bilgi ON uye_bilgisi.kullanici_id = arac_bilgi.kullanici_id " +
                 "AND uye_bilgisi.uye_no = arac_bilgi.uye_no " +
                 "WHERE " + kolon + " = ? AND uye_bilgisi.kullanici_id = ?";

    PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1, aranacak);
    pst.setInt(2, Session.kullaniciId); // sadece giriş yapan kişinin verileri

    ResultSet rs = pst.executeQuery();

    if (rs.next()) {
        String bilgi = "Üye No: " + rs.getString("uye_no") +
                       "\nAdı: " + rs.getString("ad") +
                       "\nPlaka: " + rs.getString("plaka");
        JOptionPane.showMessageDialog(null, bilgi);
    } else {
        JOptionPane.showMessageDialog(null, "Kayıt bulunamadı.");
    }

    con.close();
    arama_yap_texfald.setText("");

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Hata: " + e.getMessage());
    e.printStackTrace();
}

    }//GEN-LAST:event_aramaYapActionPerformed

    private void geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriActionPerformed
        NavigationManager.navigateTo(this, new AnaEkran());
    }//GEN-LAST:event_geriActionPerformed

    private void uye_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uye_silActionPerformed
        String secim = seccim_buttonu.getSelectedItem().toString();
    String aranacak = arama_yap_texfald.getText().trim();
    String kolon = "";

    if (aranacak.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Lütfen aranacak bilgiyi girin.");
        return;
    }

    if (secim.equals("Üye No")) {
        kolon = "uye_bilgisi.uye_no";
    } else if (secim.equals("Üye Adı")) {
        kolon = "uye_bilgisi.ad";
    } else if (secim.equals("Üye plaka")) {
        kolon = "arac_bilgi.plaka";
    }

    try {
       Connection con = DBConnection.getConnection();


        // Bilgiyi getir
        String sql = "SELECT uye_bilgisi.uye_no, uye_bilgisi.ad, arac_bilgi.plaka FROM uye_bilgisi " +
                     "INNER JOIN arac_bilgi ON uye_bilgisi.kullanici_id = arac_bilgi.kullanici_id " +
                     "AND uye_bilgisi.uye_no = arac_bilgi.uye_no " +
                     "WHERE " + kolon + " = ? AND uye_bilgisi.kullanici_id = ?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, aranacak);
        ps.setInt(2, Session.kullaniciId);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            int uyeNo = rs.getInt("uye_no");
            String ad = rs.getString("ad");
            String plaka = rs.getString("plaka");

            // Bilgileri göster
            String mesaj = "Üye No: " + uyeNo +
                           "\nAdı: " + ad +
                           "\nPlaka: " + plaka +
                           "\n\nBu üyeyi silmek istiyor musunuz?";
            int onay = JOptionPane.showConfirmDialog(null, mesaj, "Üye Silme Onayı", JOptionPane.YES_NO_OPTION);

            if (onay == JOptionPane.YES_OPTION) {
                // Araç bilgisini sil
                String silArac = "DELETE FROM arac_bilgi WHERE uye_no = ? AND kullanici_id = ?";
                PreparedStatement del1 = con.prepareStatement(silArac);
                del1.setInt(1, uyeNo);
                del1.setInt(2, Session.kullaniciId);
                del1.executeUpdate();

                // Üye bilgisini sil
                String silUye = "DELETE FROM uye_bilgisi WHERE uye_no = ? AND kullanici_id = ?";
                PreparedStatement del2 = con.prepareStatement(silUye);
                del2.setInt(1, uyeNo);
                del2.setInt(2, Session.kullaniciId);
                del2.executeUpdate();

                JOptionPane.showMessageDialog(null, "Üye başarıyla silindi.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Üye bulunamadı.");
        }

        arama_yap_texfald.setText("");
        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Hata: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_uye_silActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arama_islemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arama_islemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arama_islemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arama_islemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arama_islemi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aramaYap;
    private javax.swing.JTextField arama_yap_texfald;
    private javax.swing.JButton geri;
    private javax.swing.JLabel jLabel1;
    private otopark.RoundedPanel roundedPanel1;
    private otopark.RoundedPanel roundedPanel2;
    private javax.swing.JComboBox<String> seccim_buttonu;
    private javax.swing.JButton uye_sil;
    // End of variables declaration//GEN-END:variables
}
