/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package otopark;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;


/**
 *
 * @author asus
 */
public class Kayit_Ol extends javax.swing.JFrame {

    /**
     * Creates new form Kayit_Ol
     */
    public Kayit_Ol() {
        initComponents();
        
        // Başlangıçta odaklanmasın
JLabel dummy = new JLabel();
this.add(dummy);  // Form'a geçici bileşen ekle
dummy.setFocusable(true);
dummy.requestFocusInWindow();

// Kullanıcı Adı Placeholder
kullaniciadi.setText("Kullanıcı Adı");
kullaniciadi.setForeground(Color.GRAY);

kullaniciadi.addFocusListener(new java.awt.event.FocusAdapter() {
    public void focusGained(java.awt.event.FocusEvent evt) {
        if (kullaniciadi.getText().equals("Kullanıcı Adı")) {
            kullaniciadi.setText("");
            kullaniciadi.setForeground(Color.BLACK);
        }
    }
    public void focusLost(java.awt.event.FocusEvent evt) {
        if (kullaniciadi.getText().isEmpty()) {
            kullaniciadi.setText("Kullanıcı Adı");
            kullaniciadi.setForeground(Color.GRAY);
        }
    }
});

// Şifre Placeholder
sifre1.setText("Şifre");
sifre1.setForeground(Color.GRAY);

sifre1.addFocusListener(new java.awt.event.FocusAdapter() {
    public void focusGained(java.awt.event.FocusEvent evt) {
        if (sifre1.getText().equals("Şifre")) {
            sifre1.setText("");
            sifre1.setForeground(Color.BLACK);
        }
    }
    public void focusLost(java.awt.event.FocusEvent evt) {
        if (sifre1.getText().isEmpty()) {
            sifre1.setText("Şifre");
            sifre1.setForeground(Color.GRAY);
        }
    }
});
this.setResizable(false);           // Büyütmeyi engeller
this.setDefaultCloseOperation(EXIT_ON_CLOSE);
this.setLocationRelativeTo(null);
this.setExtendedState(javax.swing.JFrame.NORMAL);
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new otopark.RoundedPanel();
        roundedPanel2 = new otopark.RoundedPanel();
        roundedPanel3 = new otopark.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sifre1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kullaniciadi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        roundedPanel1.setBackground(new java.awt.Color(38, 43, 43));

        roundedPanel2.setBackground(new java.awt.Color(120, 120, 120));

        javax.swing.GroupLayout roundedPanel3Layout = new javax.swing.GroupLayout(roundedPanel3);
        roundedPanel3.setLayout(roundedPanel3Layout);
        roundedPanel3Layout.setHorizontalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        roundedPanel3Layout.setVerticalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KAYIT OL");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kullanıcı Adınız");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Şifreniz");

        jButton1.setBackground(new java.awt.Color(120, 120, 120));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("KAYDET");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(120, 120, 120));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\Otopark\\Otopark\\Otopark\\src\\otopark\\icon_klasoru\\6820523_back_interface_ui_ux_icon.png")); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(roundedPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1))
                    .addGroup(roundedPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sifre1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(kullaniciadi, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(roundedPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roundedPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(kullaniciadi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(sifre1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(59, 59, 59)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String kullaniciAdi = kullaniciadi.getText().trim();
String sifre = sifre1.getText();
if (!isValidUsername(kullaniciAdi)) {
    JOptionPane.showMessageDialog(this,
        "Geçersiz kullanıcı adı.\n" +
        "- 5-20 karakter olmalı\n" +
        "- Harfle başlamalı (Türkçe harfler dahil)\n" +
        "- Sadece harf, rakam ve alt çizgi (_) içermeli\n" +
        "- 'admin', 'kullanici', 'test' gibi kelimeler içermemeli.");
     // Alanları temizle (isteğe bağlı)
    kullaniciadi.setText("");
   
    return;
}



// Boşluk veya placeholder kontrolü
if (kullaniciAdi.isEmpty() || kullaniciAdi.equals("Kullanıcı Adı") ||
    sifre.isEmpty() || sifre.equals("Şifre")) {
    JOptionPane.showMessageDialog(this, "Lütfen geçerli bir kullanıcı adı ve şifre girin.");
    return;
}

// Şifre güvenlik kontrolü
if (!isStrongPassword(sifre)) {
    JOptionPane.showMessageDialog(this, "Şifre en az 8 karakter olmalı ve en az bir büyük harf, bir küçük harf, bir rakam ve bir özel karakter içermelidir.");
     // Alanları temizle (isteğe bağlı)
    
    sifre1.setText("");
    return;
}

try (Connection conn = DBConnection.getConnection()) {
    String sql = "INSERT INTO uye_kayit (kullanici_adi, kullanici_sifre) VALUES (?, ?)";
    
    // RETURN_GENERATED_KEYS ile kullanıcı_id'yi alacağız
    try (PreparedStatement ps = conn.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS)) {
        ps.setString(1, kullaniciAdi);
        ps.setString(2, sifre);
        ps.executeUpdate();

        // Yeni kullanıcı_id'yi al
        ResultSet rs = ps.getGeneratedKeys();
        if (rs.next()) {
            int yeniKullaniciId = rs.getInt(1);
            Session.kullaniciId = yeniKullaniciId; // 💥 BURASI KRİTİK
            System.out.println("Yeni kullanıcı ID: " + yeniKullaniciId); // test amaçlı log
        }
    }

    JOptionPane.showMessageDialog(this, "Kayıt başarılı!");

// Yeni Otopark ekranını aç
javax.swing.JFrame otoparkFrame = new javax.swing.JFrame("Otopark Girişi");
otoparkFrame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
otoparkFrame.setContentPane(new Otopark_Otomasyonu());
otoparkFrame.pack();
otoparkFrame.setResizable(false);
otoparkFrame.setLocationRelativeTo(null);
otoparkFrame.setVisible(true);

// Bu pencereyi kapat
this.dispose();

    // Alanları temizle (isteğe bağlı)
    kullaniciadi.setText("");
    sifre1.setText("");

} catch (java.sql.SQLException ex) {
    Logger.getLogger(Kayit_Ol.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(this, "Kayıt sırasında bir hata oluştu: " + ex.getMessage());
}
// MySQL "duplicate entry" için hata kodu: 1062
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
               // Giriş ekranını yeni pencere olarak aç
    javax.swing.JFrame otoparkFrame = new javax.swing.JFrame("Otopark Girişi");
    otoparkFrame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    otoparkFrame.setContentPane(new Otopark_Otomasyonu());
    otoparkFrame.pack();
    otoparkFrame.setResizable(false);
    otoparkFrame.setLocationRelativeTo(null);
    otoparkFrame.setVisible(true);

    // Kayıt ekranını kapat
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kayit_Ol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kayit_Ol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kayit_Ol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kayit_Ol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kayit_Ol().setVisible(true);
                
            }
        });
    }

    private void DBConnection() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField kullaniciadi;
    private otopark.RoundedPanel roundedPanel1;
    private otopark.RoundedPanel roundedPanel2;
    private otopark.RoundedPanel roundedPanel3;
    private javax.swing.JTextField sifre1;
    // End of variables declaration//GEN-END:variables
private boolean isStrongPassword(String password) {
    return password.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^a-zA-Z0-9]).{8,}$");
}
// Kullanıcı adı geçerlilik kontrolü (Türkçe karakter destekli)
private boolean isValidUsername(String username) {
    String uname = username.toLowerCase();

    // Yasaklı kelimeler
    String[] forbidden = {"admin", "root", "kullanici", "user", "test", "guest"};

    // Uzunluk kontrolü
    if (username.length() < 5 || username.length() > 20) {
        return false;
    }

    // Harfle başlamalı (Türkçe harfler dahil)
    if (!Character.isLetter(username.charAt(0))) {
        return false;
    }

    // Geçerli karakterler: harf (Türkçe dahil), rakam, alt çizgi
    if (!username.matches("^[a-zA-ZçÇğĞıİöÖşŞüÜ0-9_]+$")) {
        return false;
    }

    // Yasaklı kelime içeriyorsa
    for (String bad : forbidden) {
        if (uname.contains(bad)) {
            return false;
        }
    }

    return true;
}

}
