package otopark;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.time.Duration;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;
import java.sql.*;
import java.sql.Timestamp;
import javax.swing.JLabel;
import otopark.AnaEkran;
import otopark.DBConnection;
import otopark.NavigationManager;
import static otopark.Session.kullaniciId;




public class Otopark_Girs extends javax.swing.JFrame {

   private final Map<javax.swing.JButton, LocalDateTime> girisZamanlari = new HashMap<>();

private final Map<JButton, JLabel> butonLabelMap = new HashMap<>();

private final int dakikalikUcret = 1; // 1 dakika = 1 TL

    public Otopark_Girs() {
    initComponents();
    park_alani1.setActionCommand("1");
    park_alani2.setActionCommand("2");
    park_alani3.setActionCommand("3");
    park_alani4.setActionCommand("4");
    park_alani5.setActionCommand("5");
    park_alani6.setActionCommand("6");
    park_alani7.setActionCommand("7");
    park_alani8.setActionCommand("8");
    park_alani9.setActionCommand("9");
    park_alani10.setActionCommand("10");
    eslestirmeleriYap();        // Önce eşleştir
    parkDurumlariniYukle();     // Sonra GUI'yi doldur
    flatlafStilUygula();
geri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otopark/icon_klasoru/6820523_back_interface_ui_ux_icon.png")));

    this.setResizable(false);
    this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    this.setLocationRelativeTo(null);
    this.setExtendedState(javax.swing.JFrame.NORMAL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new otopark.RoundedPanel();
        park_alani1 = new javax.swing.JButton();
        park_alani2 = new javax.swing.JButton();
        park_alani3 = new javax.swing.JButton();
        park_alani4 = new javax.swing.JButton();
        park_alani5 = new javax.swing.JButton();
        park_alani6 = new javax.swing.JButton();
        park_alani7 = new javax.swing.JButton();
        park_alani8 = new javax.swing.JButton();
        park_alani9 = new javax.swing.JButton();
        park_alani10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        geri = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        label_Plaka1 = new javax.swing.JLabel();
        label_Plaka2 = new javax.swing.JLabel();
        label_Plaka3 = new javax.swing.JLabel();
        label_Plaka4 = new javax.swing.JLabel();
        label_Plaka5 = new javax.swing.JLabel();
        label_Plaka6 = new javax.swing.JLabel();
        label_Plaka7 = new javax.swing.JLabel();
        label_Plaka8 = new javax.swing.JLabel();
        label_Plaka9 = new javax.swing.JLabel();
        label_Plaka10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        roundedPanel1.setBackground(new java.awt.Color(120, 120, 120));

        park_alani1.setBackground(new java.awt.Color(0, 204, 102));
        park_alani1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        park_alani1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        park_alani1.setPreferredSize(new java.awt.Dimension(114, 177));
        park_alani1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                park_alani1ActionPerformed(evt);
            }
        });

        park_alani2.setBackground(new java.awt.Color(0, 204, 102));
        park_alani2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        park_alani2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        park_alani2.setPreferredSize(new java.awt.Dimension(114, 177));
        park_alani2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                park_alani2ActionPerformed(evt);
            }
        });

        park_alani3.setBackground(new java.awt.Color(0, 204, 102));
        park_alani3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        park_alani3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        park_alani3.setPreferredSize(new java.awt.Dimension(114, 177));
        park_alani3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                park_alani3ActionPerformed(evt);
            }
        });

        park_alani4.setBackground(new java.awt.Color(0, 204, 102));
        park_alani4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        park_alani4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        park_alani4.setPreferredSize(new java.awt.Dimension(114, 177));
        park_alani4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                park_alani4ActionPerformed(evt);
            }
        });

        park_alani5.setBackground(new java.awt.Color(0, 204, 102));
        park_alani5.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        park_alani5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        park_alani5.setPreferredSize(new java.awt.Dimension(114, 177));
        park_alani5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                park_alani5ActionPerformed(evt);
            }
        });

        park_alani6.setBackground(new java.awt.Color(0, 204, 102));
        park_alani6.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        park_alani6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        park_alani6.setPreferredSize(new java.awt.Dimension(114, 177));
        park_alani6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                park_alani6ActionPerformed(evt);
            }
        });

        park_alani7.setBackground(new java.awt.Color(0, 204, 102));
        park_alani7.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        park_alani7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        park_alani7.setPreferredSize(new java.awt.Dimension(114, 177));
        park_alani7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                park_alani7ActionPerformed(evt);
            }
        });

        park_alani8.setBackground(new java.awt.Color(0, 204, 102));
        park_alani8.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        park_alani8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        park_alani8.setPreferredSize(new java.awt.Dimension(114, 177));
        park_alani8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                park_alani8ActionPerformed(evt);
            }
        });

        park_alani9.setBackground(new java.awt.Color(0, 204, 102));
        park_alani9.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        park_alani9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        park_alani9.setPreferredSize(new java.awt.Dimension(114, 177));
        park_alani9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                park_alani9ActionPerformed(evt);
            }
        });

        park_alani10.setBackground(new java.awt.Color(0, 204, 102));
        park_alani10.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        park_alani10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        park_alani10.setPreferredSize(new java.awt.Dimension(114, 177));
        park_alani10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                park_alani10ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("   OTOPARK ALANI");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 7));

        geri.setBackground(new java.awt.Color(120, 120, 120));
        geri.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        geri.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\Otopark\\Otopark\\Otopark\\src\\otopark\\icon_klasoru\\6820523_back_interface_ui_ux_icon.png")); // NOI18N
        geri.setBorder(null);
        geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        label_Plaka1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        label_Plaka2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        label_Plaka3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        label_Plaka4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        label_Plaka5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        label_Plaka6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        label_Plaka7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        label_Plaka8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        label_Plaka9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        label_Plaka10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                                        .addComponent(label_Plaka6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(label_Plaka7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                                        .addComponent(park_alani6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(park_alani7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                                        .addComponent(label_Plaka8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(label_Plaka9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(label_Plaka10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                                        .addComponent(park_alani8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(park_alani9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(park_alani10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(park_alani1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label_Plaka1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label_Plaka2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(park_alani2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(label_Plaka3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(label_Plaka4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(park_alani4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(park_alani3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(32, 32, 32)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(park_alani5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label_Plaka5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(geri, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(park_alani1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(park_alani2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(park_alani5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(park_alani4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(park_alani3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Plaka4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_Plaka5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label_Plaka1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_Plaka3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_Plaka2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_Plaka7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_Plaka8)
                        .addComponent(label_Plaka6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_Plaka9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_Plaka10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(park_alani10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(park_alani9, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(park_alani8, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(park_alani7, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(park_alani6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(geri, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriActionPerformed
        NavigationManager.navigateTo(this, new AnaEkran()); 
    }//GEN-LAST:event_geriActionPerformed

    private void park_alani10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_park_alani10ActionPerformed
         parkIslemYap(park_alani10);
    }//GEN-LAST:event_park_alani10ActionPerformed

    private void park_alani2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_park_alani2ActionPerformed
          parkIslemYap(park_alani2);
       

    }//GEN-LAST:event_park_alani2ActionPerformed

    private void park_alani5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_park_alani5ActionPerformed
          parkIslemYap(park_alani5);
    }//GEN-LAST:event_park_alani5ActionPerformed

    private void park_alani7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_park_alani7ActionPerformed
        parkIslemYap(park_alani7);

    }//GEN-LAST:event_park_alani7ActionPerformed

    private void park_alani8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_park_alani8ActionPerformed
        
    parkIslemYap(park_alani8);
    }//GEN-LAST:event_park_alani8ActionPerformed

    private void park_alani9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_park_alani9ActionPerformed
          parkIslemYap(park_alani9);
    }//GEN-LAST:event_park_alani9ActionPerformed

    private void park_alani4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_park_alani4ActionPerformed
        
    parkIslemYap(park_alani4);
    }//GEN-LAST:event_park_alani4ActionPerformed

    private void park_alani3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_park_alani3ActionPerformed
       
    parkIslemYap(park_alani3);
    }//GEN-LAST:event_park_alani3ActionPerformed

    private void park_alani6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_park_alani6ActionPerformed
     
            parkIslemYap(park_alani6);

    }//GEN-LAST:event_park_alani6ActionPerformed

    private void park_alani1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_park_alani1ActionPerformed
      
            parkIslemYap(park_alani1);
    }//GEN-LAST:event_park_alani1ActionPerformed
private void parkDurumlariniYukle() {
    JButton[] butonlar = {
        park_alani1, park_alani2, park_alani3, park_alani4, park_alani5,
        park_alani6, park_alani7, park_alani8, park_alani9, park_alani10
    };

    JLabel[] plakalar = {
        label_Plaka1, label_Plaka2, label_Plaka3, label_Plaka4, label_Plaka5,
        label_Plaka6, label_Plaka7, label_Plaka8, label_Plaka9, label_Plaka10
    };

    try (Connection conn = DBConnection.getConnection()) {
        for (int i = 0; i < butonlar.length; i++) {
            String butonNo = String.valueOf(i + 1);
            String sql = "SELECT plaka, model_adi FROM park_kayitlari WHERE buton_no = ? AND aktif_mi = TRUE AND kullanici_id = ?";
            try (PreparedStatement ps = conn.prepareStatement(sql)) {
                ps.setString(1, butonNo);
                ps.setInt(2, Session.kullaniciId);
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    // Park doluysa
                    butonlar[i].setBackground(Color.RED);
                    plakalar[i].setText(rs.getString("plaka"));
                    plakalar[i].setForeground(Color.WHITE);

                    // 👇 Model bilgisine göre ikon yükle
                    String modelAdi = rs.getString("model_adi");
                    String iconDosyaAdi;

                    switch (modelAdi.toLowerCase()) {
                        case "otomobil" -> iconDosyaAdi = "otomobil.png";
                        case "taksi" -> iconDosyaAdi = "taksi.png";
                        case "motorsiklet" -> iconDosyaAdi = "motorsiklet.png";
                        case "kamyonet" -> iconDosyaAdi = "kamyonet.png";
                        default -> iconDosyaAdi = null;
                    }

                    if (iconDosyaAdi != null) {
                        String kaynakYolu = "/otopark/icon_klasoru/" + iconDosyaAdi;
                        butonlar[i].setIcon(new javax.swing.ImageIcon(getClass().getResource(kaynakYolu)));
                    }

                } else {
                    // Park boşsa
                    butonlar[i].setBackground(new Color(0, 204, 102));
                    plakalar[i].setText("");
                    butonlar[i].setIcon(null); // ikon varsa temizle
                }
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Park durumları yüklenemedi: " + e.getMessage());
    }
}

   private double getDakikalikUcret(String modelAdi) {
    double dakikalikUcret = 0.0;

    try (Connection conn = DBConnection.getConnection()) {
        String sql = "SELECT saatlik FROM ucret_bilgisi WHERE model_tur = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, modelAdi);
        ResultSet rs = ps.executeQuery();  // ← Bu satır mutlaka olmalı!

        if (rs.next()) {
            double saatlik = rs.getDouble("saatlik");
            dakikalikUcret = saatlik / 60.0;
        } else {
            JOptionPane.showMessageDialog(null, modelAdi + " için ücret bilgisi bulunamadı.");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Ücret bilgisi alınamadı: " + e.getMessage());
        e.printStackTrace();
    }

    return dakikalikUcret;
}


private void parkIslemYap(JButton btn) {
    Color yesil = new Color(0, 204, 102);
    Color kirmizi = Color.RED;

    try (Connection conn = DBConnection.getConnection()) {
         String butonNo = btn.getActionCommand(); // "1", "2", ..., "10"
        String sql = "SELECT * FROM park_kayitlari WHERE buton_no = ? AND aktif_mi = TRUE AND kullanici_id = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, butonNo);
        ps.setInt(2, Session.kullaniciId);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            // ÇIKIŞ
            LocalDateTime giris = rs.getTimestamp("giris_zamani").toLocalDateTime();
            LocalDateTime cikis = LocalDateTime.now();
            long dakika = Duration.between(giris, cikis).toMinutes();

            String modelAdi = rs.getString("model_adi");
            double dakikaBasiUcret = getDakikalikUcret(modelAdi);
            int ucret = (int) Math.ceil(dakika * dakikaBasiUcret);

            String updateSQL = "UPDATE park_kayitlari SET cikis_zamani = ?, ucret = ?, aktif_mi = FALSE WHERE id = ?";
            PreparedStatement update = conn.prepareStatement(updateSQL);
            update.setTimestamp(1, Timestamp.valueOf(cikis));
            update.setInt(2, ucret);
            update.setInt(3, rs.getInt("id"));
            update.executeUpdate();

            JOptionPane.showMessageDialog(null,
                "Plaka: " + rs.getString("plaka") +
                "\nModel: " + modelAdi +
                "\nSüre: " + dakika + " dk\nÜcret: " + ucret + " TL");
            

            btn.setBackground(yesil);
            // Plaka label'ını temizle
            JLabel plakaLabel = butonLabelMap.get(btn);
            if (plakaLabel != null) {
            plakaLabel.setText("");
            btn.setIcon(null); // <== Bu satır ikonları temizler
}

        } else {
            // GİRİŞ
            String plaka = JOptionPane.showInputDialog(this, "Plaka girin:");
            if (plaka == null || plaka.trim().isEmpty()) return;

            String[] modeller = {"Otomobil", "Taksi", "Motorsiklet", "Kamyonet"};
            String modelAdi = (String) JOptionPane.showInputDialog(this, "Araç modelini seçin:", "Model Seçimi",
            JOptionPane.QUESTION_MESSAGE, null, modeller, modeller[0]);
               if (modelAdi == null || modelAdi.trim().isEmpty()) return;

            
          String iconDosyaAdi;

            switch (modelAdi.toLowerCase()) {
            case "otomobil": iconDosyaAdi = "otomobil.png"; break;
            case "taksi": iconDosyaAdi = "taksi.png"; break;
            case "motorsiklet": iconDosyaAdi = "motorsiklet.png"; break;
            case "kamyonet": iconDosyaAdi = "kamyonet.png"; break;
            default:
                JOptionPane.showMessageDialog(this, "Geçersiz model.");
                return;
        }

        // 🔄 Butonun iconunu güncelle
        String kaynakYolu = "/otopark/icon_klasoru/" + iconDosyaAdi;
        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource(kaynakYolu)));

            String insertSQL = "INSERT INTO park_kayitlari (buton_no, plaka, model_adi, giris_zamani, kullanici_id, aktif_mi) VALUES (?, ?, ?, ?, ?, TRUE)";
            PreparedStatement insert = conn.prepareStatement(insertSQL);
            insert.setString(1, butonNo);
            insert.setString(2, plaka);
            insert.setString(3, modelAdi);
            insert.setTimestamp(4, Timestamp.valueOf(LocalDateTime.now()));
            insert.setInt(5, kullaniciId);
            insert.executeUpdate();

            btn.setBackground(kirmizi);
            JLabel plakaLabel = butonLabelMap.get(btn);
if (plakaLabel != null) {
    plakaLabel.setText(plaka);
    plakaLabel.setForeground(Color.white);
}
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Hata: " + ex.getMessage());
        ex.printStackTrace();
    }
}private void eslestirmeleriYap() {
    butonLabelMap.put(park_alani1, label_Plaka1);
    butonLabelMap.put(park_alani2, label_Plaka2);
    butonLabelMap.put(park_alani3, label_Plaka3);
    butonLabelMap.put(park_alani4, label_Plaka4);
    butonLabelMap.put(park_alani5, label_Plaka5);
    butonLabelMap.put(park_alani6, label_Plaka6);
    butonLabelMap.put(park_alani7, label_Plaka7);
    butonLabelMap.put(park_alani8, label_Plaka8);
    butonLabelMap.put(park_alani9, label_Plaka9);
    butonLabelMap.put(park_alani10, label_Plaka10);
} private void flatlafStilUygula() {
        JButton[] butonlar = {
            park_alani1, park_alani2, park_alani3, park_alani4, park_alani5,
            park_alani6, park_alani7, park_alani8, park_alani9, park_alani10, park_alani2
        };

        for (JButton btn : butonlar) {
            btn.setFont(new Font("Segoe UI", Font.BOLD, 20));
            btn.setForeground(Color.WHITE);
          
            btn.setFocusPainted(false);
            btn.putClientProperty("JButton.buttonType", "roundRect");
        }
    }






    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Otopark_Girs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Otopark_Girs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Otopark_Girs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Otopark_Girs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Otopark_Girs().setVisible(true);
}
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton geri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel label_Plaka1;
    private javax.swing.JLabel label_Plaka10;
    private javax.swing.JLabel label_Plaka2;
    private javax.swing.JLabel label_Plaka3;
    private javax.swing.JLabel label_Plaka4;
    private javax.swing.JLabel label_Plaka5;
    private javax.swing.JLabel label_Plaka6;
    private javax.swing.JLabel label_Plaka7;
    private javax.swing.JLabel label_Plaka8;
    private javax.swing.JLabel label_Plaka9;
    private javax.swing.JButton park_alani1;
    private javax.swing.JButton park_alani10;
    private javax.swing.JButton park_alani2;
    private javax.swing.JButton park_alani3;
    private javax.swing.JButton park_alani4;
    private javax.swing.JButton park_alani5;
    private javax.swing.JButton park_alani6;
    private javax.swing.JButton park_alani7;
    private javax.swing.JButton park_alani8;
    private javax.swing.JButton park_alani9;
    private otopark.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables

}